name: Linter

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.2.0
        env:
          VALIDATE_CSHARP: true
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "dev"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: ".*Assets/Scripts/.*"