name: Run test

on:
  pull_request:
    branches: [ dev ]

jobs:
  run-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Running Test
        run: |
          echo "PWD is $PWD"
          echo "Running test"
          echo "Test passed"